### PR TITLE
Fix Bug to convert the GC types to the python types.

### PR DESCRIPTION
**Pull request by SohamTilekar**

### CODE REVIEW

**Comment by SohamTilekar** [comment]
Done

**Comment by SohamTilekar** [comment]
Fix this shit Bug in the Shit maintainer language maintained by shit programmer, Creates bugs using AI

**Comment by SohamTilekar** [comment]
This pull request introduces the `auto_magic_methods` decorator to automate the addition of magic methods to several classes in the `src/interpreter/base.py` file. The decorator simplifies the code by reducing redundancy and ensuring consistency across different classes.

Key changes include:

### Introduction of `auto_magic_methods` Decorator:
* Added the `auto_magic_methods` decorator to automate the addition of common magic methods to classes. (`src/interpreter/base.py`, [src/interpreter/base.pyL35-R74](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L35-R74))

### Application of `auto_magic_methods` Decorator:
* Applied the `auto_magic_methods` decorator to the `ExpressionResult` class. (`src/interpreter/base.py`, [src/interpreter/base.pyL270-R307](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L270-R307))
* Applied the `auto_magic_methods` decorator to the `BLError` class. (`src/interpreter/base.py`, [src/interpreter/base.pyL388-R425](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L388-R425))
* Applied the `auto_magic_methods` decorator to the `Value` class and its subclasses (`Bool`, `Null`, `String`, `Int`, `Float`). (`src/interpreter/base.py`, [[1]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262R451) [[2]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262R470) [[3]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262R485) [[4]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L461-R501) [[5]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262R550) [[6]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L540-R581) [[7]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L578-R643) [[8]](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262R698)

### Corrections and Improvements:
* Corrected the method call in `String.multiply` from `super().add` to `super().multiply`. (`src/interpreter/base.py`, [src/interpreter/base.pyL461-R501](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L461-R501))
* Corrected the method call in `Int.multiply` from `super().multiply` to `super().multiply`. (`src/interpreter/base.py`, [src/interpreter/base.pyL540-R581](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L540-R581))
* Corrected the method calls in `Int` class for bitwise operations to use the correct super method. (`src/interpreter/base.py`, [src/interpreter/base.pyL578-R643](diffhunk://#diff-d2f95e5b18ef546d0366b73f403e0eec5cd4e25c95f5b7a999ad9eb2b64a8262L578-R643))

These changes enhance the maintainability and readability of the code by reducing redundancy and ensuring that magic methods are consistently applied across various classes.

**Comment by dangduomg** [comment]
> Fix this shit Bug in the Shit maintainer language maintained by shit programmer, Creates bugs using AI

i never use ai lol

**Pull request merged**
